# -*- coding: utf-8 -*-
"""Kong Island.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11RkMUiLmH2_Ff_G6zS6xDOx6CL4-L7TU
"""

print('''
                  /\  ____ 
                  <> ( oo )
                  <>_| ^^ |_ 
                  <>   @    \
                 /~~\ . . _ |
                /~~~~\    | |
               /~~~~~~\/ _| |
               |[][][]/ / [m]
               |[][][[m]
               |[][][]|
               |[][][]|
               |[][][]|
               |[][][]|
               |[][][]|
               |[][][]|
               |[][][]|
               |[][][]|
               |[|--|]|
               |[|  |]|
               ======== 
              ==========
              |[[    ]]|
              ==========      
''')
print("Welcome to the Kong Island! You have to reach your friend King Kong the Mighty Monkey Lord to save you from other terrible beasts.")
dir = input("\nYou were sleeping now you wake up on a new island. Where would you like to go? Left or Right?")
dir = dir.lower()
if dir == 'right':
  print("You fell into a booby trap made by giant worms. Game Over!")
elif dir == 'left':
  print("You find a lake. Do you want to swim or wait for boat?")
  method = input()
  method = method.lower()
  if method == 'swim':
    print("Eh! You get eaten by giant crocodile. Game Over!")
  elif method == 'wait':
    print("Congrats you are on 3rd and last level of this game")
    print("There are 3 doors in front of you. Red, Yellow and Green but only one of them leads to King Kong others are a way of brutal death if you pick right door you win or else you die!")
    door = input()
    door = door.lower()
    if door == 'red':
      print("Wrong Choice! You get caught up in Horde of Walkers and they eat you alive!")
    elif door == 'yellow':
      print("Congrats! You meet Kong he feeds and welcomes you! and promises to get u back to your land")
    elif door == 'green':
      print("Wrong Choice! You get caught up in Horde of Mighty Elephants and you get crushed under their feet!")
    else:
      print("Invalid choice! You get eaten by Kong's rival T-Rex.")
  else:
    print("Invalid choice! You get eaten by Kong's rival T-Rex.")
  
else:
  print("Invalid choice! You get eaten by Kong's rival T-Rex.")
